version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    restart: always
    volumes:
      - ./api:/api/
    ports:
      - "5000:3000"
    environment:
      MY_ENV_VAR: test

  mongo:
    build:
      context: .
      dockerfile: docker/Dockerfile-mongo
    restart: always
    volumes:
      - ./api:/api/
      - ./data:/data/db
    ports:
      - "27020:27017"
