version: '3'
services:
  web_api:
    build:
      context: .
      dockerfile: docker/Dockerfile-web_api
    restart: always
    volumes:
      - ./api:/api/
    ports:
      - "3000:3000"
    environment:
      MY_ENV_VAR: test

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile-frontend
    restart: always
    volumes:
      - ./frontend:/frontend/
    ports:
      - "4000:4000"
    environment:
      MY_ENV_VAR: test

  mongo:
    build:
      context: .
      dockerfile: docker/Dockerfile-mongo
    restart: always
    volumes:
      - ./api:/api/
      - ./data:/data/db
    ports:
      - "27020:27017"
